-- AlterTable
ALTER TABLE `Timer` MODIFY `description` VARCHAR(191) NULL,
    MODIFY `startDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `endDate` DATETIME(3) NULL,
    MODIFY `status` VARCHAR(191) NULL,
    MODIFY `duration` INTEGER NULL,
    MODIFY `category` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `Watcher` MODIFY `start` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
